# Generated by Django 3.1.2 on 2020-10-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20201002_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
