# Generated by Django 3.1.2 on 2020-10-03 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_auto_20201002_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='-', max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('oil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.oiltype')),
            ],
        ),
    ]
