# Generated by Django 3.1.2 on 2020-10-03 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_billinghistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='billinghistory',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='billinghistory',
            name='total',
            field=models.IntegerField(default=100),
        ),
    ]
