# Generated by Django 3.1.2 on 2020-10-03 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_auto_20201003_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='oil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.oiltype'),
        ),
    ]
