# Generated by Django 3.1.2 on 2020-10-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_auto_20201003_0449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billinghistory',
            name='total',
        ),
        migrations.AddField(
            model_name='billinghistory',
            name='amount',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
        migrations.AlterField(
            model_name='billinghistory',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=5, null=True),
        ),
    ]
